export const ACTION_RESET_FORM = 'RESET_FORM';
export const ACTION_SUBMIT_FORM = 'SUBMIT_FORM';
export const ACTION_SET_FORM_DIRTY = 'SET_FORM_DIRTY';
export const ACTION_SET_FIELD_VALUE = 'SET_FIELD_VALUE';
export const ACTION_SET_FIELD_TOUCHED = 'SET_FIELD_TOUCHED';
export const ACTION_SET_SUBMITTING_PROCESS = 'SET_SUBMITTING_PROCESS';
export const ACTION_SET_ERROR_MESSAGES = 'ACTION_SET_ERROR_MESSAGES';


